<?php
     define("DATABASE_HOST","localhost");
     define("DATABASE_USER","root");
     define("DATABASE_PASSWORD","");
     define("DATABASE_PORT",3306);
     define("DATABASE_NAME","GRNPN_KSKCH");
     define("GP_USER_RESOURCE_PATH","../../resources");
     define("GP_USER_DEFAULT_PROFILE_PIC","GP_def_profile_pic_1.jpg");
     define("GP_USER_DEFAULT_PROJECT_POSTER","GP_def_project_poster_1.jpg");
?>